# Generated by Django 5.1.4 on 2024-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('img_path', models.TextField(max_length=255, verbose_name='Путь до картинки')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
            ],
        ),
    ]
