# Generated by Django 5.1.4 on 2024-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Сломано'), (1, 'В норме'), (2, 'Новое')], default=2, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
