# Generated by Django 5.1.4 on 2024-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_description_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'сломано'), (1, 'в норме'), (2, 'новое')], verbose_name='Статус'),
        ),
    ]
