# Generated by Django 5.1.4 on 2024-12-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_current_holder_remove_item_img_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='FirtstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='SecondtName',
            new_name='secondName',
        ),
    ]
