# Generated by Django 5.1.4 on 2024-12-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_firtstname_item_firstname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='secondName',
        ),
        migrations.AddField(
            model_name='item',
            name='current_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='текущий владелей'),
        ),
    ]
