# Generated by Django 5.1.4 on 2025-01-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_current_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_holder',
            field=models.CharField(max_length=255, verbose_name='текущий владелец'),
        ),
    ]
