# Generated by Django 5.1.4 on 2025-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_item_current_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='количество'),
        ),
    ]
