# Generated by Django 5.1.4 on 2025-01-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
