# Generated by Django 5.1.4 on 2025-01-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_path',
            field=models.CharField(max_length=255, null=True, verbose_name='фото'),
        ),
    ]
