# Generated by Django 5.1.4 on 2025-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_path',
            field=models.CharField(max_length=255, null=True, verbose_name='qr-код'),
        ),
    ]
